CREATE TABLE UTENTE (
    CODICE_FISCALE CHAR(16) NOT NULL,
    NOME VARCHAR(50) NOT NULL,
    COGNOME VARCHAR(50) NOT NULL,
    TELEFONO VARCHAR(15),
    EMAIL VARCHAR(100) NOT NULL,
    PRIMARY KEY (CODICE_FISCALE)
);

CREATE TABLE ZONA (
    NOME VARCHAR(50) NOT NULL,
    AREA_CITTA VARCHAR(50) NOT NULL,
    COSTO DECIMAL(5,2) NOT NULL,
    PRIMARY KEY (NOME, AREA_CITTA)
);

CREATE TABLE CATEGORIA_VEICOLO (
    NOME_CATEGORIA VARCHAR(30) NOT NULL,
    PRIMARY KEY (NOME_CATEGORIA)
);

CREATE TABLE SCONTO (
    ID_SCONTO INTEGER NOT NULL,
    PERCENTUALE_SCONTO INTEGER NOT NULL,
    DATA_SCADENZA DATE NOT NULL,
    TIPO_SCONTO VARCHAR(50) NOT NULL,
    PRIMARY KEY (ID_SCONTO)
);

CREATE TABLE PERSONALE (
    CODICE_FISCALE CHAR(16) NOT NULL,
    COGNOME VARCHAR(50) NOT NULL,
    NOME VARCHAR(50) NOT NULL,
    PRIMARY KEY (CODICE_FISCALE)
);

-- SPOSTATA IN ALTO: Deve esistere prima di TURNO, MULTA e CONTROLLARE
CREATE TABLE CONTROLLORE (
    PERSONALE_CODICE_FISCALE CHAR(16) NOT NULL,
    PRIMARY KEY (PERSONALE_CODICE_FISCALE),
    FOREIGN KEY (PERSONALE_CODICE_FISCALE) REFERENCES PERSONALE (CODICE_FISCALE)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);

-- SPOSTATA IN ALTO: Deve esistere prima di ASSEGNATO_A
CREATE TABLE OPERATORE (
    PERSONALE_CODICE_FISCALE CHAR(16) NOT NULL,
    PRIMARY KEY (PERSONALE_CODICE_FISCALE),
    FOREIGN KEY (PERSONALE_CODICE_FISCALE) REFERENCES PERSONALE (CODICE_FISCALE)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);

CREATE TABLE ABBONAMENTO (
    ID_ABBONAMENTO INTEGER NOT NULL,
    DATA_INIZIO DATE NOT NULL,
    DATA_FINE DATE NOT NULL,
    UTENTE_CODICE_FISCALE CHAR(16) NOT NULL,
    PRIMARY KEY (ID_ABBONAMENTO),
    FOREIGN KEY (UTENTE_CODICE_FISCALE) REFERENCES UTENTE (CODICE_FISCALE)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);

CREATE TABLE PARCHEGGIO (
    ID_PARCHEGGIO INTEGER NOT NULL,
    NOME_PARCHEGGIO VARCHAR(100) NOT NULL,
    CAPIENZA_TOTALE INTEGER NOT NULL,
    ORARIO_APERTURA TIME,
    Type VARCHAR(10) NOT NULL,
    ZONA_NOME VARCHAR(50) NOT NULL,
    ZONA_AREA_CITTA VARCHAR(50) NOT NULL,
    PRIMARY KEY (ID_PARCHEGGIO),
    FOREIGN KEY (ZONA_NOME, ZONA_AREA_CITTA) REFERENCES ZONA (NOME, AREA_CITTA)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);

-- SPOSTATA IN ALTO: Deve esistere dopo PARCHEGGIO e PERSONALE
CREATE TABLE RESPONSABILE (
    PERSONALE_CODICE_FISCALE CHAR(16) NOT NULL,
    PARCHEGGIO_ID_PARCHEGGIO INTEGER NOT NULL,
    PRIMARY KEY (PERSONALE_CODICE_FISCALE),
    FOREIGN KEY (PERSONALE_CODICE_FISCALE) REFERENCES PERSONALE (CODICE_FISCALE)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    FOREIGN KEY (PARCHEGGIO_ID_PARCHEGGIO) REFERENCES PARCHEGGIO (ID_PARCHEGGIO)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);

CREATE TABLE VEICOLO (
    TARGA VARCHAR(10) NOT NULL,
    CATEGORIA_VEICOLO_NOME_CATEGORIA VARCHAR(30) NOT NULL,
    UTENTE_CODICE_FISCALE CHAR(16),
    PRIMARY KEY (TARGA),
    FOREIGN KEY (CATEGORIA_VEICOLO_NOME_CATEGORIA) REFERENCES CATEGORIA_VEICOLO (NOME_CATEGORIA)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    FOREIGN KEY (UTENTE_CODICE_FISCALE) REFERENCES UTENTE (CODICE_FISCALE)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);

CREATE TABLE SOSTA (
    ID_SOSTA INTEGER NOT NULL,
    ORA_INIZIO TIME NOT NULL,
    ORA_FINE TIME,
    DATA_INIZIO DATE NOT NULL,
    PARCHEGGIO_ID_PARCHEGGIO INTEGER NOT NULL,
    VEICOLO_TARGA VARCHAR(10) NOT NULL,
    ABBONAMENTO_ID_ABBONAMENTO INTEGER,
    SCONTO_ID_SCONTO INTEGER,
    PRIMARY KEY (ID_SOSTA),
    FOREIGN KEY (PARCHEGGIO_ID_PARCHEGGIO) REFERENCES PARCHEGGIO (ID_PARCHEGGIO)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    FOREIGN KEY (VEICOLO_TARGA) REFERENCES VEICOLO (TARGA)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    FOREIGN KEY (ABBONAMENTO_ID_ABBONAMENTO) REFERENCES ABBONAMENTO (ID_ABBONAMENTO)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    FOREIGN KEY (SCONTO_ID_SCONTO) REFERENCES SCONTO (ID_SCONTO)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);

CREATE TABLE TURNO (
    ID_TURNO INTEGER NOT NULL,
    ORA_FINE TIME NOT NULL,
    ORA_INIZIO TIME NOT NULL,
    DATA_TURNO DATE NOT NULL,
    CONTROLLORE_PERSONALE_CODICE_FISCALE CHAR(16) NOT NULL,
    PRIMARY KEY (ID_TURNO),
    FOREIGN KEY (CONTROLLORE_PERSONALE_CODICE_FISCALE) REFERENCES CONTROLLORE (PERSONALE_CODICE_FISCALE)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);

CREATE TABLE MULTA (
    ID_MULTA INTEGER NOT NULL,
    DATA DATE NOT NULL,
    ORA TIME NOT NULL,
    IMPORTO DECIMAL(5,2) NOT NULL,
    DESCRIZIONE VARCHAR(255) NOT NULL,
    CONTROLLORE_PERSONALE_CODICE_FISCALE CHAR(16) NOT NULL,
    VEICOLO_TARGA VARCHAR(10) NOT NULL,
    PRIMARY KEY (ID_MULTA),
    FOREIGN KEY (CONTROLLORE_PERSONALE_CODICE_FISCALE) REFERENCES CONTROLLORE (PERSONALE_CODICE_FISCALE)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    FOREIGN KEY (VEICOLO_TARGA) REFERENCES VEICOLO (TARGA)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);

CREATE TABLE BIGLIETTO (
    ID_BIGLIETTO INTEGER NOT NULL,
    DATA_ACQUISTO DATE NOT NULL,
    VALIDITA BOOLEAN NOT NULL,
    SOSTA_ID_SOSTA INTEGER NOT NULL,
    PRIMARY KEY (ID_BIGLIETTO),
    FOREIGN KEY (SOSTA_ID_SOSTA) REFERENCES SOSTA (ID_SOSTA)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);

CREATE TABLE VALUTARE (
    UTENTE_CODICE_FISCALE CHAR(16) NOT NULL,
    PARCHEGGIO_ID_PARCHEGGIO INTEGER NOT NULL,
    DATA_VALUTAZIONE DATE NOT NULL,
    VAL_SICUREZZA INTEGER NOT NULL,
    VAL_PULIZIA INTEGER NOT NULL,
    PRIMARY KEY (UTENTE_CODICE_FISCALE, PARCHEGGIO_ID_PARCHEGGIO),
    FOREIGN KEY (UTENTE_CODICE_FISCALE) REFERENCES UTENTE (CODICE_FISCALE)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    FOREIGN KEY (PARCHEGGIO_ID_PARCHEGGIO) REFERENCES PARCHEGGIO (ID_PARCHEGGIO)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);

CREATE TABLE DISPONIBILITA (
    PARCHEGGIO_ID_PARCHEGGIO INTEGER NOT NULL,
    CATEGORIA_VEICOLO_NOME_CATEGORIA VARCHAR(30) NOT NULL,
    CAPIENZA_CATEGORIA INTEGER NOT NULL,
    POSTI_DISPONIBILI_CATEGORIA INTEGER NOT NULL,
    PRIMARY KEY (PARCHEGGIO_ID_PARCHEGGIO, CATEGORIA_VEICOLO_NOME_CATEGORIA),
    FOREIGN KEY (PARCHEGGIO_ID_PARCHEGGIO) REFERENCES PARCHEGGIO (ID_PARCHEGGIO)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    FOREIGN KEY (CATEGORIA_VEICOLO_NOME_CATEGORIA) REFERENCES CATEGORIA_VEICOLO (NOME_CATEGORIA)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);

CREATE TABLE USUFRUIRE (
    UTENTE_CODICE_FISCALE CHAR(16) NOT NULL,
    SCONTO_ID_SCONTO INTEGER NOT NULL,
    PRIMARY KEY (UTENTE_CODICE_FISCALE, SCONTO_ID_SCONTO),
    FOREIGN KEY (UTENTE_CODICE_FISCALE) REFERENCES UTENTE (CODICE_FISCALE)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    FOREIGN KEY (SCONTO_ID_SCONTO) REFERENCES SCONTO (ID_SCONTO)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);

CREATE TABLE CONTROLLARE (
    PARCHEGGIO_ID_PARCHEGGIO INTEGER NOT NULL,
    CONTROLLORE_PERSONALE_CODICE_FISCALE CHAR(16) NOT NULL,
    PRIMARY KEY (PARCHEGGIO_ID_PARCHEGGIO, CONTROLLORE_PERSONALE_CODICE_FISCALE),
    FOREIGN KEY (PARCHEGGIO_ID_PARCHEGGIO) REFERENCES PARCHEGGIO (ID_PARCHEGGIO)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    FOREIGN KEY (CONTROLLORE_PERSONALE_CODICE_FISCALE) REFERENCES CONTROLLORE (PERSONALE_CODICE_FISCALE)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);

CREATE TABLE ASSEGNATO_A (
    PARCHEGGIO_ID_PARCHEGGIO INTEGER NOT NULL,
    OPERATORE_PERSONALE_CODICE_FISCALE CHAR(16) NOT NULL,
    PRIMARY KEY (PARCHEGGIO_ID_PARCHEGGIO, OPERATORE_PERSONALE_CODICE_FISCALE),
    FOREIGN KEY (PARCHEGGIO_ID_PARCHEGGIO) REFERENCES PARCHEGGIO (ID_PARCHEGGIO)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    FOREIGN KEY (OPERATORE_PERSONALE_CODICE_FISCALE) REFERENCES OPERATORE (PERSONALE_CODICE_FISCALE)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);

CREATE TABLE VALIDO_IN (
    SCONTO_ID_SCONTO INTEGER NOT NULL,
    ZONA_NOME VARCHAR(50) NOT NULL,
    ZONA_AREA_CITTA VARCHAR(50) NOT NULL,
    PRIMARY KEY (SCONTO_ID_SCONTO),
    FOREIGN KEY (SCONTO_ID_SCONTO) REFERENCES SCONTO (ID_SCONTO)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    FOREIGN KEY (ZONA_NOME, ZONA_AREA_CITTA) REFERENCES ZONA (NOME, AREA_CITTA)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);