INSERT INTO UTENTE (CODICE_FISCALE, NOME, COGNOME, TELEFONO, EMAIL) VALUES
('BRTCRS90M01L219X', 'Cristian', 'Bertone', '3331234567', 'cristian.bertone@email.it'),
('CRSMNL92M15L219Y', 'Manuel', 'Cerise', '3339876543', 'manuel.cerise@email.it'),
('RSSMRA80A01L219Z', 'Mario', 'Rossi', NULL, 'mario.rossi@email.it');

INSERT INTO ZONA (NOME, AREA_CITTA, COSTO) VALUES
('Centro Storico', 'Centro', 3),
('Lingotto', 'Sud', 2),
('San Salvario', 'Sud-Est', 2);

INSERT INTO CATEGORIA_VEICOLO (NOME_CATEGORIA) VALUES
('Automobile'),
('Motociclo'),
('Furgone');

INSERT INTO SCONTO (ID_SCONTO, PERCENTUALE_SCONTO, DATA_SCADENZA, TIPO_SCONTO) VALUES
(1, 10, '2026-12-31', 'Nuovo Registrato'),
(2, 20, '2026-12-31', 'Fedeltà');

INSERT INTO PERSONALE (CODICE_FISCALE, COGNOME, NOME) VALUES
('BNCGPP75M10L219A', 'Bianchi', 'Giuseppe'),
('VRDLGI85T20L219B', 'Verdi', 'Luigi'),
('NRIMCO88P30L219C', 'Neri', 'Marco');

INSERT INTO CONTROLLORE (PERSONALE_CODICE_FISCALE) VALUES ('NRIMCO88P30L219C');
INSERT INTO OPERATORE (PERSONALE_CODICE_FISCALE) VALUES ('VRDLGI85T20L219B');

INSERT INTO ABBONAMENTO (ID_ABBONAMENTO, DATA_INIZIO, DATA_FINE, UTENTE_CODICE_FISCALE) VALUES
(1, '2026-01-01', '2026-12-31', 'BRTCRS90M01L219X');

INSERT INTO PARCHEGGIO (ID_PARCHEGGIO, NOME_PARCHEGGIO, CAPIENZA_TOTALE, ORARIO_APERTURA, Type, ZONA_NOME, ZONA_AREA_CITTA) VALUES
(1, 'Garage Roma', 200, '06:00:00', 'INTERNO', 'Centro Storico', 'Centro'),
(2, 'Piazza Nizza', 50, NULL, 'ESTERNO', 'San Salvario', 'Sud-Est');

INSERT INTO RESPONSABILE (PERSONALE_CODICE_FISCALE, PARCHEGGIO_ID_PARCHEGGIO) VALUES
('BNCGPP75M10L219A', 1);

INSERT INTO VEICOLO (TARGA, CATEGORIA_VEICOLO_NOME_CATEGORIA, UTENTE_CODICE_FISCALE) VALUES
('AA123BB', 'Automobile', 'BRTCRS90M01L219X'),
('DD456EE', 'Motociclo', 'CRSMNL92M15L219Y');

INSERT INTO SOSTA (ID_SOSTA, ORA_INIZIO, ORA_FINE, DATA_INIZIO, PARCHEGGIO_ID_PARCHEGGIO, VEICOLO_TARGA, ABBONAMENTO_ID_ABBONAMENTO, SCONTO_ID_SCONTO) VALUES
(1, '09:00:00', '11:00:00', '2026-05-10', 2, 'DD456EE', NULL, NULL),
(2, '08:00:00', NULL, '2026-05-15', 1, 'AA123BB', 1, NULL);

INSERT INTO TURNO (ID_TURNO, ORA_FINE, ORA_INIZIO, DATA_TURNO, CONTROLLORE_PERSONALE_CODICE_FISCALE) VALUES
(1, '14:00:00', '06:00:00', '2026-05-10', 'NRIMCO88P30L219C');

INSERT INTO MULTA (ID_MULTA, DATA, ORA, IMPORTO, DESCRIZIONE, CONTROLLORE_PERSONALE_CODICE_FISCALE, VEICOLO_TARGA) VALUES
(1, '2026-05-10', '10:30:00', 45, 'Sosta sulle strisce pedonali', 'NRIMCO88P30L219C', 'DD456EE');

INSERT INTO BIGLIETTO (ID_BIGLIETTO, DATA_ACQUISTO, VALIDITA, SOSTA_ID_SOSTA) VALUES
(1, '2026-05-10', 'False', 1);

INSERT INTO VALUTARE (UTENTE_CODICE_FISCALE, PARCHEGGIO_ID_PARCHEGGIO, DATA_VALUTAZIONE, VAL_SICUREZZA, VAL_PULIZIA) VALUES
('BRTCRS90M01L219X', 1, '2026-05-12', 5, 4);

INSERT INTO DISPONIBILITA (PARCHEGGIO_ID_PARCHEGGIO, CATEGORIA_VEICOLO_NOME_CATEGORIA, CAPIENZA_CATEGORIA, POSTI_DISPONIBILI_CATEGORIA) VALUES
(1, 'Automobile', 150, 149),
(1, 'Motociclo', 50, 50),
(2, 'Motociclo', 20, 20);

INSERT INTO USUFRUIRE (UTENTE_CODICE_FISCALE, SCONTO_ID_SCONTO) VALUES
('BRTCRS90M01L219X', 2);

INSERT INTO CONTROLLARE (PARCHEGGIO_ID_PARCHEGGIO, CONTROLLORE_PERSONALE_CODICE_FISCALE) VALUES
(2, 'NRIMCO88P30L219C');

INSERT INTO ASSEGNATO_A (PARCHEGGIO_ID_PARCHEGGIO, OPERATORE_PERSONALE_CODICE_FISCALE) VALUES
(1, 'VRDLGI85T20L219B');

INSERT INTO VALIDO_IN (SCONTO_ID_SCONTO, ZONA_NOME, ZONA_AREA_CITTA) VALUES
(2, 'Centro Storico', 'Centro');