UPDATE SOSTA 
SET ORA_FINE = '15:30:00' 
WHERE ID_SOSTA = 1;

UPDATE PARCHEGGIO 
SET ID_PARCHEGGIO = 99 
WHERE ID_PARCHEGGIO = 2;

DELETE FROM UTENTE 
WHERE CODICE_FISCALE = 'BRTCRS90M01L219X';

DELETE FROM BIGLIETTO 
WHERE ID_BIGLIETTO = 1;

SELECT S.ID_SOSTA, P.NOME_PARCHEGGIO, V.TARGA, U.COGNOME, U.NOME, S.ORA_INIZIO
FROM SOSTA S
JOIN PARCHEGGIO P ON S.PARCHEGGIO_ID_PARCHEGGIO = P.ID_PARCHEGGIO
JOIN VEICOLO V ON S.VEICOLO_TARGA = V.TARGA
JOIN UTENTE U ON V.UTENTE_CODICE_FISCALE = U.CODICE_FISCALE
WHERE S.ORA_FINE IS NULL;

SELECT P.NOME, P.COGNOME, COUNT(M.ID_MULTA) AS NUMERO_MULTE, SUM(M.IMPORTO) AS TOTALE_INCASSATO
FROM CONTROLLORE C
JOIN PERSONALE P ON C.PERSONALE_CODICE_FISCALE = P.CODICE_FISCALE
JOIN MULTA M ON C.PERSONALE_CODICE_FISCALE = M.CONTROLLORE_PERSONALE_CODICE_FISCALE
GROUP BY P.NOME, P.COGNOME;

SELECT A.ID_ABBONAMENTO, U.COGNOME, U.NOME, A.DATA_INIZIO, A.DATA_FINE
FROM ABBONAMENTO A
JOIN UTENTE U ON A.UTENTE_CODICE_FISCALE = U.CODICE_FISCALE
WHERE CURRENT_DATE BETWEEN A.DATA_INIZIO AND A.DATA_FINE;

SELECT P.NOME_PARCHEGGIO, Z.NOME AS ZONA, D.POSTI_DISPONIBILI_CATEGORIA
FROM PARCHEGGIO P
JOIN ZONA Z ON P.ZONA_NOME = Z.NOME AND P.ZONA_AREA_CITTA = Z.AREA_CITTA
JOIN DISPONIBILITA D ON P.ID_PARCHEGGIO = D.PARCHEGGIO_ID_PARCHEGGIO
WHERE D.CATEGORIA_VEICOLO_NOME_CATEGORIA = 'Automobile' 
AND D.POSTI_DISPONIBILI_CATEGORIA > 0;